name: Deploy Next.js site to GitHub Pages

on:
  push:
    branches:
      - main   # change if your default branch is not "main"

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18   # Next.js works well with Node 18+

      - name: Install dependencies
        run: npm ci   # faster and more reliable for CI

      - name: Build static site
        run: npm run build   # make sure your package.json build script is now just "next build"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
